// Lucide React Icons
import {
  Code2,
  GraduationCap,
  Briefcase,
  Award,
  Rocket,
  Heart,
  Coffee,
  BookOpen,
  Zap,
  Database,
  Server,
  Cloud,
  Mail,
  MapPin,
  Phone,
  Code,
  Lightbulb,
  Users,
  Palette,
  Calendar,
  Package,
  Server,
  Award,
  Cloud,
  Lightbulb,
  Smartphone,
  CheckCircle,
  Users,
  TrendingUp,
  Mobile,
  GitBranch,
  Shield,
} from "lucide-react";

// React Icons
import {
  FiGithub,
  FiLinkedin,
  FiTwitter,
  FiInstagram,
  FiCode,
} from "react-icons/fi";

// Project Images
import PROJECT_IMG_1 from "../assets/images/Focus.jpg";
import PROJECT_IMG_2 from "../assets/images/lufffy.jpg";
import PROJECT_IMG_3 from "../assets/images/luffy2.jpg";
import PROJECT_IMG_4 from "../assets/images/panda.jpg";
import PROJECT_IMG_5 from "../assets/images/racecar.jpg";
import PROJECT_IMG_6 from "../assets/images/racecar1.jpg";

// Skills Categories - Complete Detailed List
export const SKILLS_CATEGORY = [
  {
    id: 1,
    title: "Frontend Development",
    icon: Code2,
    description:
      "Building sophisticated and responsive user interfaces with modern frameworks and tools.",
    skills: [
      { name: "React", level: "Advanced", color: "bg-blue-700" },
      { name: "Next.js", level: "Advanced", color: "bg-blue-700" },
      { name: "Redux", level: "Advanced", color: "bg-blue-700" },
      { name: "TypeScript", level: "Advanced", color: "bg-blue-700" },
      { name: "JavaScript", level: "Advanced", color: "bg-blue-700" },
      { name: "HTML5", level: "Advanced", color: "bg-blue-700" },
      { name: "CSS3", level: "Advanced", color: "bg-blue-700" },
      { name: "Tailwind CSS", level: "Advanced", color: "bg-blue-700" },
      { name: "Bootstrap", level: "Advanced", color: "bg-blue-700" },
      { name: "Vite", level: "Advanced", color: "bg-blue-700" },
      { name: "SASS/SCSS", level: "Advanced", color: "bg-blue-700" },
      {
        name: "Styled Components",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      { name: "Material-UI", level: "Intermediate", color: "bg-blue-500" },
      { name: "Angular", level: "Beginner", color: "bg-blue-400" },
    ],
  },
  {
    id: 2,
    title: "Backend Development",
    icon: Server,
    description:
      "Architecting scalable and resilient server-side infrastructures and APIs.",
    skills: [
      { name: "Node.js", level: "Advanced", color: "bg-blue-700" },
      { name: "Express.js", level: "Advanced", color: "bg-blue-700" },
      { name: "REST API", level: "Advanced", color: "bg-blue-700" },
      { name: "JWT", level: "Advanced", color: "bg-blue-700" },
      { name: "Socket.io", level: "Intermediate", color: "bg-blue-500" },
      { name: "Mongoose", level: "Advanced", color: "bg-blue-700" },
      { name: "GraphQL", level: "Intermediate", color: "bg-blue-500" },
      { name: "Python", level: "Beginner", color: "bg-blue-500" },
      { name: "Microservices", level: "Intermediate", color: "bg-blue-500" },
      { name: "Redis", level: "Intermediate", color: "bg-blue-500" },
      { name: "Message Queues", level: "Beginner", color: "bg-blue-400" },
      { name: "RabbitMQ", level: "Beginner", color: "bg-blue-400" },
      { name: "EJS", level: "Intermediate", color: "bg-blue-500" },
    ],
  },
  {
    id: 3,
    title: "Database Management",
    icon: Database,
    description:
      "Designing and managing efficient database solutions with optimization and modeling expertise.",
    skills: [
      { name: "MongoDB", level: "Advanced", color: "bg-blue-700" },
      { name: "MySQL", level: "Intermediate", color: "bg-blue-500" },
      { name: "PostgreSQL", level: "Intermediate", color: "bg-blue-500" },
      { name: "Firebase", level: "Intermediate", color: "bg-blue-500" },
      { name: "Redis", level: "Intermediate", color: "bg-blue-500" },
      { name: "SQLite", level: "Intermediate", color: "bg-blue-500" },
      { name: "Database Design", level: "Advanced", color: "bg-blue-700" },
      { name: "Data Modeling", level: "Intermediate", color: "bg-blue-500" },
      { name: "ORM", level: "Intermediate", color: "bg-blue-500" },
      { name: "Sequelize", level: "Intermediate", color: "bg-blue-500" },
      {
        name: "Database Optimization",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      { name: "SQL", level: "Intermediate", color: "bg-blue-500" },
    ],
  },
  {
    id: 4,
    title: "Architecture & Design",
    icon: Award,
    description:
      "Implementing robust architectural patterns, design principles and system architecture.",
    skills: [
      { name: "MVC Architecture", level: "Advanced", color: "bg-blue-700" },
      { name: "Clean Architecture", level: "Advanced", color: "bg-blue-700" },
      { name: "Multi-tenant Design", level: "Advanced", color: "bg-blue-700" },
      {
        name: "Microservices Architecture",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      {
        name: "Event-Driven Architecture",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      { name: "System Design", level: "Intermediate", color: "bg-blue-500" },
      { name: "API Design", level: "Advanced", color: "bg-blue-700" },
      { name: "Design Patterns", level: "Advanced", color: "bg-blue-700" },
      { name: "SOLID Principles", level: "Advanced", color: "bg-blue-700" },
      { name: "Figma", level: "Intermediate", color: "bg-blue-500" },
    ],
  },
  {
    id: 5,
    title: "DevOps & Deployment",
    icon: Cloud,
    description:
      "Deploying and managing applications with modern DevOps practices and cloud infrastructure.",
    skills: [
      { name: "AWS EC2", level: "Advanced", color: "bg-blue-700" },
      { name: "AWS Lambda", level: "Intermediate", color: "bg-blue-500" },
      { name: "Route 53", level: "Intermediate", color: "bg-blue-500" },
      { name: "Docker", level: "Intermediate", color: "bg-blue-500" },
      { name: "Kubernetes", level: "Beginner", color: "bg-blue-400" },
      { name: "NGINX", level: "Advanced", color: "bg-blue-700" },
      { name: "PM2", level: "Intermediate", color: "bg-blue-500" },
      { name: "GitHub Actions", level: "Intermediate", color: "bg-blue-500" },
      { name: "Jenkins", level: "Beginner", color: "bg-blue-400" },
      { name: "Vercel", level: "Advanced", color: "bg-blue-700" },
      { name: "Grafana", level: "Beginner", color: "bg-blue-400" },
      { name: "Prometheus", level: "Beginner", color: "bg-blue-400" },
      { name: "Git", level: "Advanced", color: "bg-blue-700" },
      { name: "Postman", level: "Advanced", color: "bg-blue-700" },
      { name: "VS Code", level: "Advanced", color: "bg-blue-700" },
    ],
  },
  {
    id: 6,
    title: "Algorithms & Problem Solving",
    icon: Lightbulb,
    description:
      "Strong foundation in data structures, algorithmic thinking and system optimization.",
    skills: [
      { name: "Data Structures", level: "Intermediate", color: "bg-blue-500" },
      { name: "Algorithms", level: "Intermediate", color: "bg-blue-500" },
      { name: "Problem Solving", level: "Advanced", color: "bg-blue-700" },
      { name: "System Design", level: "Intermediate", color: "bg-blue-500" },
      { name: "Code Optimization", level: "Advanced", color: "bg-blue-700" },
      { name: "Big O Notation", level: "Advanced", color: "bg-blue-700" },
      { name: "LeetCode", level: "Intermediate", color: "bg-blue-500" },
      { name: "HackerRank", level: "Intermediate", color: "bg-blue-500" },
    ],
  },
  {
    id: 7,
    title: "Testing & Quality Assurance",
    icon: CheckCircle,
    description:
      "Ensuring code quality and reliability through comprehensive testing strategies.",
    skills: [
      { name: "Jest", level: "Intermediate", color: "bg-blue-500" },
      {
        name: "React Testing Library",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      { name: "Unit Testing", level: "Advanced", color: "bg-blue-700" },
      {
        name: "Integration Testing",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      {
        name: "End-to-End Testing",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      {
        name: "Test-Driven Development",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      { name: "Performance Testing", level: "Beginner", color: "bg-blue-400" },
    ],
  },
  {
    id: 9,
    title: "Professional Skills",
    icon: Users,
    description:
      "Collaboration, communication, and project management abilities for team success.",
    skills: [
      { name: "Agile Methodology", level: "Advanced", color: "bg-blue-700" },
      { name: "Scrum", level: "Advanced", color: "bg-blue-700" },
      { name: "Git/GitHub", level: "Advanced", color: "bg-blue-700" },
      {
        name: "Technical Documentation",
        level: "Advanced",
        color: "bg-blue-700",
      },
      {
        name: "Project Management",
        level: "Intermediate",
        color: "bg-blue-500",
      },
      { name: "Communication Skills", level: "Advanced", color: "bg-blue-700" },
      { name: "Problem Analysis", level: "Advanced", color: "bg-blue-700" },
    ],
  },
  {
    id: 10,
    title: "Emerging Technologies",
    icon: Zap,
    description:
      "Exploring cutting-edge technologies and modern development trends.",
    skills: [
      { name: "AI/ML Integration", level: "Beginner", color: "bg-blue-400" },
      { name: "Machine Learning", level: "Beginner", color: "bg-blue-400" },
      {
        name: "Serverless Architecture",
        level: "Intermediate",
        color: "bg-blue-500",
      },
    ],
  },
];

// Tech Stack - Categorized Version
export const TECH_STACK_DETAILED = {
  frontend: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Vue.js",
    "Angular",
    "HTML5",
    "CSS3",
    "Tailwind CSS",
    "Bootstrap",
    "SASS/SCSS",
    "Styled Components",
    "Material-UI",
    "Redux",
    "Zustand",
  ],
  backend: ["Node.js", "Express.js", "REST API", "Socket.io", "JWT"],
  database: [
    "MongoDB",
    "Mongoose",
    "MySQL",
    "PostgreSQL",
    "Redis",
    "Firebase",
    "SQLite",
    "Sequelize",
  ],
  cloud_devops: [
    "AWS",
    "AWS EC2",
    "Docker",
    "Kubernetes",
    "NGINX",
    "PM2",
    "Vercel",
    "GitHub Actions",
  ],
  tools: ["Git", "VS Code", "Vite", "Postman", "Figma", "Jest"],
  services: ["Razorpay", "Stripe", "Twilio", "Google Analytics"],
};

// Flattened version for easy display
export const TECH_STACK = Object.values(TECH_STACK_DETAILED).flat();

// Statistics
export const STATS = [
  { number: "6+", label: "Major Projects" },
  { number: "2+", label: "Years Experience" },
  { number: "20+", label: "Technologies" },
  { number: "100%", label: "Code Quality" },
];

// Social Media Links
export const SOCIAL_LINKS = [
  {
    name: "GitHub",
    icon: FiGithub,
    url: "https://github.com/abilashhhh",
    color: "hover:text-gray-400",
    bgColor: "hover:bg-gray-800",
  },
  {
    name: "LinkedIn",
    icon: FiLinkedin,
    url: "https://linkedin.com/in/abilash2001",
    color: "hover:text-blue-400",
    bgColor: "hover:bg-blue-900",
  },
  {
    name: "LeetCode",
    icon: FiCode,
    url: "https://leetcode.com/u/abilashn2001/",
    color: "hover:text-orange-400",
    bgColor: "hover:bg-orange-900",
  },
  {
    name: "Instagram",
    icon: FiInstagram,
    url: "https://instagram.com/abilash_._",
    color: "hover:text-pink-400",
    bgColor: "hover:bg-pink-900",
  },
  // {
  //   name: "Twitter",
  //   icon: FiTwitter,
  //   url: "https://twitter.com",
  //   color: "hover:text-sky-400",
  //   bgColor: "hover:bg-sky-900",
  // },
];

// Contact Information
export const CONTACT_INFO = [
  {
    icon: MapPin,
    label: "Location",
    value: "Bengaluru, Karnataka",
  },
  {
    icon: Mail,
    label: "Email",
    value: "mailto:abilashncty@gmail.com",
    value2: "abilashncty@gmail.com",
  },
  {
    icon: Phone,
    label: "Phone",
    value: "+91 79022 53958",
  },
  {
    icon: Calendar,
    label: "Availability",
    value: "Open to opportunities",
  },
];

// Projects
export const PROJECTS = [
  {
    id: 1,
    title: "Trend Trove - Social Media & News Platform",
    description:
      "Trend Trove - A comprehensive social media and news feed platform built with Clean Architecture, featuring high-quality video/audio calls, instant messaging, ephemeral stories, and AI-powered image captioning using Clarifai.",
    detailedDescription:
      "A full-featured social media and news feed platform combining real-time news with core social features. Includes high-quality video/audio calls (Zego Cloud), instant messaging, ephemeral stories, and AI-powered image captioning (Clarifai). Integrated Razorpay for secure payments and premium features.",
    image: PROJECT_IMG_1,
    tags: ["TypeScript", "React", "Node.js", "MongoDB", "Socket.io"],
    tagsDetailed: [
      "TypeScript",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Firebase",
      "Tailwind CSS",
      "Redux",
      "Zustand",
      "Clarifai",
      "Zego Cloud",
      "Razorpay",
      "JWT",
      "Nodemailer",
      "Socket.io",
      "DaisyUI",
      "Clean Architecture",
    ],
    liveUrl: "#",
    githubUrl: "#",
    featured: true,
    category: "Full Stack",
    features: [
      "Token-based authentication & Google login",
      "Profile management & privacy controls",
      "Explore and feed pages with real-time news",
      "High-quality video/audio calls via Zego Cloud",
      "Instant messaging & real-time notifications",
      "Ephemeral stories and highlights",
      "AI-powered image captioning (Clarifai)",
      "Post tagging, saving, and hashtag support",
      "User blocking/unblocking functionality",
      "Admin dashboard with user management",
      "Dark mode support & ReCAPTCHA protection",
      "Secure payments via Razorpay integration",
      "Premium subscription features",
    ],
    technicalHighlights: [
      "Clean Architecture implementation",
      "Real-time communication with Socket.io",
      "JWT token authentication system",
      "Google OAuth integration",
      "AI integration for image processing",
      "Payment gateway integration",
      "Responsive design with Tailwind CSS",
    ],
    role: "Full Stack Developer",
    duration: "3 months",
    status: "Completed",
    projectType: "Personal Project",
  },
  {
    id: 2,
    title: "Zigma Watches - E-commerce Platform",
    description:
      "Zigma Watches - An e-commerce web application for selling smartwatches built using MVC architecture, featuring coupon support, referral systems, order tracking, and secure payments via Razorpay integration.",
    detailedDescription:
      "An online smartwatch store built using MVC architecture offering a smooth shopping experience with features like coupon support, referral systems, order tracking, and secure payments via Razorpay. Includes comprehensive admin tools for sales reporting and inventory management.",
    image: PROJECT_IMG_2,
    tags: ["Node.js", "Express", "MongoDB", "EJS", "Bootstrap"],
    tagsDetailed: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "EJS",
      "HTML",
      "CSS",
      "Bootstrap",
      "JavaScript",
      "Nginx",
      "PM2",
      "AWS",
      "Razorpay",
      "Nodemailer",
    ],
    liveUrl: "https://www.zigmawatches.shop",
    githubUrl: "#",
    featured: true,
    category: "Full Stack",
    features: [
      "User authentication and authorization",
      "Product catalog with category management",
      "Shopping cart and wishlist functionality",
      "Secure payment processing via Razorpay",
      "Coupon system and referral program",
      "Wallet system for payments",
      "Order tracking and invoice generation",
      "Return and cancel order options",
      "Product rating and review system",
      "Banner management for marketing",
      "OTP confirmation via email",
      "Product image zoom functionality",
    ],
    technicalHighlights: [
      "MVC Architecture pattern",
      "AWS EC2 deployment with Nginx",
      "PM2 process management",
      "SSL certificate integration",
      "RESTful API design",
      "Responsive Bootstrap design",
      "Session-based authentication",
    ],
    adminFeatures: [
      "Sales reporting with charts and graphs",
      "User management (block/unblock)",
      "Product and category management",
      "Order management system",
      "Coupon and offer management",
    ],
    role: "Full Stack Developer",
    duration: "2 months",
    status: "Live Production",
    projectType: "Personal Project",
  },
  {
    id: 3,
    title: "Checkpoint Systems - Multi-tenant SaaS",
    description:
      "A robust multi-tenant architecture application with isolated customer data through separate MongoDB databases, featuring dynamic database switching, connection pooling, and tenant-specific UI customizations.",
    detailedDescription:
      "Enterprise multi-tenant application designed with robust architecture to isolate customer data by provisioning separate MongoDB databases for each client. Features dynamic database switching, connection pooling, and AG Grid components for optimal performance.",
    image: PROJECT_IMG_3,
    tags: ["React", "AG Grid", "MongoDB", "Node.js", "TypeScript"],
    tagsDetailed: [
      "React",
      "AG Grid",
      "MongoDB",
      "Node.js",
      "TypeScript",
      "Express.js",
      "Multi-tenant Architecture",
      "Connection Pooling",
      "Dynamic Database Switching",
    ],
    liveUrl: "",
    githubUrl: "",
    featured: false,
    category: "Full Stack",
    features: [
      "Multi-tenant architecture with data isolation",
      "Dynamic database switching per client",
      "Connection pooling for performance optimization",
      "Modular and responsive UI components",
      "AG Grid integration for dynamic tables",
      "Tenant-specific customizations",
      "Secure resource allocation",
    ],
    technicalHighlights: [
      "Separate MongoDB databases per tenant",
      "High availability architecture",
      "Optimized performance across concurrent sessions",
      "Secure data isolation",
      "Dynamic component rendering",
    ],
    role: "Full Stack Developer",
    duration: "Ongoing",
    status: "",
    projectType: "Professional Project",
  },
  {
    id: 4,
    title: "ART HEALTH - Healthcare Platform",
    description:
      "A healthcare platform with dynamic and responsive UI screens, featuring automated workflows for generating dynamic emails and PDFs, and implementing subscription-based dynamic tables for users.",
    detailedDescription:
      "Healthcare application featuring dynamic and responsive UI design with automated workflow systems for event confirmations and notifications through dynamic emails and PDF generation.",
    image: PROJECT_IMG_4,
    tags: ["React", "Node.js", "MongoDB", "PDF Generation", "Email Automation"],
    tagsDetailed: [
      "React",
      "Node.js",
      "MongoDB",
      "PDF Generation",
      "Email Automation",
      "Responsive Design",
      "Dynamic Tables",
      "Workflow Automation",
    ],
    liveUrl: "",
    githubUrl: "",
    featured: false,
    category: "Full Stack",
    features: [
      "Dynamic and responsive UI screens",
      "Automated workflow systems",
      "Dynamic email generation and delivery",
      "PDF generation for event confirmations",
      "Subscription-based dynamic tables",
      "Customized user experiences by plan level",
    ],
    technicalHighlights: [
      "Seamless cross-device user experience",
      "Automated notification system",
      "Dynamic content rendering based on user subscription",
      "Responsive design implementation",
    ],
    role: "Full Stack Developer",
    duration: "2 months",
    status: "",
    projectType: "Professional Project",
  },
  {
    id: 5,
    title: "db-connections-util - NPM Package",
    description:
      "A security-first NPM package for parsing, encrypting, and reconstructing database connection strings. Supports MongoDB, PostgreSQL, MySQL, Redis, SQL Server, and Azure CosmosDB with AES-256 encryption.",
    detailedDescription:
      "A robust and security-first utility package designed to parse, encrypt, and reconstruct database connection strings for multiple database types, supporting both cloud and on-premise environments with AES-256 encryption.",
    image: PROJECT_IMG_5,
    tags: ["Node.js", "TypeScript", "Security", "NPM", "Database"],
    tagsDetailed: [
      "Node.js",
      "TypeScript",
      "Security",
      "NPM",
      "Database",
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "SQL Server",
      "Azure CosmosDB",
      "AES-256 Encryption",
      "Connection Strings",
    ],
    liveUrl: "https://www.npmjs.com/package/db-connections-util",
    githubUrl: "#",
    featured: true,
    category: "Backend",
    features: [
      "Parse and reconstruct database connection strings",
      "AES-256 encryption of credentials",
      "Support for multiple database types",
      "Cloud and on-premise environment support",
      "Structured parsing and type detection",
      "Detailed reconstruction capabilities",
    ],
    technicalHighlights: [
      "Security-first design approach",
      "Multi-database support (MongoDB Atlas/Compass, PostgreSQL, MySQL, Redis cluster, SQL Server, Azure CosmosDB)",
      "AES-256 encryption implementation",
      "Public NPM module publication",
      "TypeScript implementation",
    ],
    role: "Package Author & Developer",
    duration: "1 month",
    status: "Published on NPM",
    projectType: "Personal Project",
  },
  {
    id: 6,
    title: "Hospital Management System",
    description:
      "A streamlined application for managing hospital operations with modules for receptionists and doctors, featuring automated token generation, appointment management, and prescription handling with 10-day SLA.",
    detailedDescription:
      "Comprehensive hospital management system with specialized modules for receptionists and doctors, featuring automated token generation based on appointment dates and doctors, with 10-day SLA accounting for holidays.",
    image: PROJECT_IMG_6,
    tags: ["React", "Node.js", "MongoDB", "Neutrinos Studio"],
    tagsDetailed: [
      "React",
      "Node.js",
      "MongoDB",
      "Neutrinos Studio",
      "Hospital Management",
      "Token System",
      "Appointment Scheduling",
      "Prescription Management",
    ],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
    category: "Full Stack",
    features: [
      "Department and doctor management",
      "Appointment booking system",
      "Automated token generation",
      "10-day SLA with holiday consideration",
      "Prescription uploading and management",
      "Receptionist and doctor modules",
    ],
    modules: {
      receptionist: [
        "Department Management",
        "Doctor Management",
        "Booking Management",
        "Token Generation",
      ],
      doctor: ["Appointment Viewing", "Prescription Uploading"],
    },
    technicalHighlights: [
      "Automated token generation system",
      "SLA-based appointment scheduling",
      "Role-based access control",
      "Holiday-aware scheduling system",
    ],
    role: "Full Stack Developer",
    duration: "1 month",
    status: "Completed",
    projectType: "Personal Project",
  },
  {
    id: 7,
    title: "Event Registration System",
    description:
      "A simple yet effective application designed to manage events with full CRUD functionality, search and filter features for easy event discovery and management.",
    detailedDescription:
      "Event management system with comprehensive CRUD operations, search functionality, and filtering capabilities for efficient event organization and discovery.",
    image: PROJECT_IMG_1,
    tags: ["React", "JavaScript", "CSS3", "CRUD", "Search"],
    tagsDetailed: [
      "React",
      "JavaScript",
      "CSS3",
      "CRUD Operations",
      "Search & Filter",
      "Event Management",
      "Neutrinos Studio",
    ],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
    category: "Full Stack",
    features: [
      "Create, read, update, delete events",
      "Advanced search functionality",
      "Filter events by various criteria",
      "User-friendly interface",
    ],
    technicalHighlights: [
      "Full CRUD implementation",
      "Efficient search and filter algorithms",
      "Responsive design",
    ],
    role: "Full Stack Developer",
    duration: "2 weeks",
    status: "Completed",
    projectType: "Personal Project",
  },
  {
    id: 8,
    title: "Smart Task Manager",
    description:
      "A feature-rich todo application with drag-and-drop functionality, task categories, due dates, and progress tracking. Built with React and local storage persistence.",
    detailedDescription:
      "Advanced task management application with drag-and-drop interface, categorization system, due date tracking, and visual progress indicators with local storage for data persistence.",
    image: PROJECT_IMG_1,
    tags: ["React", "JavaScript", "CSS3", "Local Storage", "UI/UX"],
    tagsDetailed: [
      "React",
      "JavaScript",
      "CSS3",
      "Local Storage",
      "Drag & Drop",
      "Task Management",
      "Progress Tracking",
      "Due Dates",
      "Categories",
    ],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
    category: "Frontend",
    features: [
      "Drag-and-drop task organization",
      "Task categorization and tagging",
      "Due date tracking and reminders",
      "Progress tracking with visual indicators",
      "Local storage data persistence",
      "Responsive mobile-friendly design",
    ],
    technicalHighlights: [
      "Drag and drop implementation",
      "Local storage integration",
      "Progress visualization",
      "Responsive UI/UX design",
    ],
    role: "Frontend Developer",
    duration: "1 week",
    status: "Completed",
    projectType: "Personal Project",
  },
  {
    id: 9,
    title: "Weather Management Application",
    description:
      "A real-time weather application with location detection, 5-day forecast, interactive charts, and weather alerts using OpenWeather API.",
    detailedDescription:
      "Comprehensive weather application providing real-time updates, extended forecasts, and weather-related news with location-based services and interactive data visualization.",
    image: PROJECT_IMG_4,
    tags: ["JavaScript", "API", "Chart.js", "Geolocation", "CSS3"],
    tagsDetailed: [
      "JavaScript",
      "OpenWeather API",
      "Chart.js",
      "Geolocation API",
      "CSS3",
      "Weather Data",
      "Forecast",
      "Real-time Updates",
    ],
    liveUrl: "#",
    githubUrl: "#",
    featured: false,
    category: "Frontend",
    features: [
      "Real-time weather updates",
      "5-day weather forecast",
      "Location detection services",
      "Temperature, humidity, and condition display",
      "Interactive weather charts",
      "Weather event news and alerts",
    ],
    technicalHighlights: [
      "OpenWeather API integration",
      "Geolocation services",
      "Chart.js data visualization",
      "Responsive design",
    ],
    role: "Frontend Developer",
    duration: "1 week",
    status: "Completed",
    projectType: "Personal Project",
  },
];

// Passions
export const PASSIONS = [
  {
    icon: Code2,
    title: "Clean Architecture",
    description: "Building scalable and maintainable codebases",
  },
  {
    icon: Zap,
    title: "Performance",
    description: "Optimizing applications for speed and efficiency",
  },
  {
    icon: Lightbulb,
    title: "Innovation",
    description: "Staying ahead with cutting-edge technologies",
  },
  {
    icon: Database,
    title: "Data Architecture",
    description: "Designing robust multi-tenant database solutions",
  },
  {
    icon: Rocket,
    title: "Problem Solving",
    description: "Turning complex challenges into elegant solutions",
  },
  {
    icon: Shield,
    title: "Security",
    description: "Implementing robust security practices and protocols",
  },
  {
    icon: GitBranch,
    title: "DevOps",
    description: "Streamlining development and deployment pipelines",
  },
  {
    icon: Mobile,
    title: "Responsive Design",
    description: "Creating seamless experiences across all devices",
  },
  {
    icon: Cloud,
    title: "Cloud Technologies",
    description: "Leveraging cloud platforms for scalable solutions",
  },
  {
    icon: TrendingUp,
    title: "Growth",
    description: "Building systems that scale with business needs",
  },
  {
    icon: Server,
    title: "Backend Development",
    description: "Crafting robust APIs and server-side logic",
  },
];

// Certifications
export const CERTIFICATIONS = [
  {
    id: 1,
    title: "Zoho CRM",
    issuer: "Zoho",
    year: "2025",
    date: "Jul 21, 2025",
    certificateUrl: "#",
    image: "/certificates/zoho-crm.jpg",
    featured: true,
    description:
      "Self-learning course on Zoho CRM covering comprehensive customer relationship management platform features and implementation.",
    skills: [
      "Zoho CRM",
      "Customer Relationship Management",
      "Sales Automation",
      "Business Process Management",
    ],
    learnings: [
      "Mastered Zoho CRM platform configuration and customization",
      "Implemented sales automation and workflow management",
      "Designed customer relationship management strategies",
      "Applied business process optimization techniques",
    ],
    validThrough: "1 Year",
    credentialId: null,
  },
  {
    id: 2,
    title: "Docker Essentials: A Developer Introduction",
    issuer: "IBM Cognitive Class",
    year: "2025",
    date: "Jul 26, 2025",
    certificateUrl:
      "https://courses.cognitiveclass.ai/certificates/70b5722ce4f34400af6cf12016d22a8e",
    image: "/certificates/docker-ibm.jpg",
    featured: true,
    description:
      "IBM certification covering Docker containerization fundamentals, image management, and container orchestration basics.",
    skills: [
      "Docker",
      "Containerization",
      "Docker Images",
      "Container Management",
      "IBM Cloud",
    ],
    learnings: [
      "Mastered Docker container creation and management",
      "Built and optimized Docker images using Dockerfiles",
      "Implemented container networking and storage solutions",
      "Applied Docker Compose for multi-container applications",
      "Understood container orchestration fundamentals",
    ],
    validThrough: null,
    credentialId: "70b5722ce4f34400af6cf12016d22a8e",
  },
  {
    id: 3,
    title: "Python Web Developer",
    issuer: "L&T EduTech",
    year: "2023",
    date: "Jul 12, 2023",
    certificateUrl: "#",
    image: "/certificates/python-lnt.jpg",
    featured: true,
    description:
      "Comprehensive Python web development program covering backend development, database integration, and web frameworks.",
    skills: [
      "Python Programming",
      "SQLite Database",
      "Web Development",
      "Backend Development",
    ],
    learnings: [
      "Developed web applications using Python frameworks",
      "Designed and implemented SQLite database schemas",
      "Built RESTful APIs and web services",
      "Applied object-oriented programming principles in Python",
    ],
    validThrough: null,
    credentialId: null,
  },
  {
    id: 4,
    title: "Git Training",
    issuer: "Simplilearn",
    year: "2024",
    date: "Apr 21, 2024",
    certificateUrl: "#",
    image: "/certificates/git-simplilearn.jpg",
    featured: false,
    description:
      "Professional Git version control training covering repository management, branching strategies, and collaborative workflows.",
    skills: [
      "Git",
      "Version Control",
      "GitHub",
      "Branching",
      "Code Collaboration",
    ],
    learnings: [
      "Mastered Git commands and repository management",
      "Implemented effective branching and merging strategies",
      "Collaborated using pull requests and code reviews",
      "Resolved merge conflicts and managed project history",
    ],
    validThrough: null,
    credentialId: "5064488",
  },
  {
    id: 5,
    title: "TypeScript: The New JavaScript for Web Development",
    issuer: "Simplilearn",
    year: "2024",
    date: "May 1, 2024",
    certificateUrl: "#",
    image: "/certificates/typescript-simplilearn.jpg",
    featured: false,
    description:
      "Comprehensive TypeScript course covering type systems, modern JavaScript features, and web development applications.",
    skills: [
      "TypeScript",
      "JavaScript",
      "Web Development",
      "Type Systems",
      "Frontend Development",
    ],
    learnings: [
      "Mastered TypeScript syntax and type annotations",
      "Applied object-oriented programming in TypeScript",
      "Integrated TypeScript with modern frameworks",
      "Implemented type-safe JavaScript applications",
    ],
    validThrough: null,
    credentialId: "5105075",
  },
  {
    id: 6,
    title: "4.0 Tech Online Bootcamp",
    issuer: "NxtWave",
    year: "2021",
    date: "Sep 2, 2021",
    certificateUrl:
      "https://certificates.ccbp.in/4-0-tech-bootcamp/?id=XG93C5M2BF",
    image: "/certificates/tech-bootcamp.jpg",
    featured: false,
    description:
      "Intensive bootcamp covering transformative Industry 4.0 technologies including AI, IoT, Data Science, and Blockchain.",
    skills: [
      "AI & ML",
      "IoT",
      "Data Science",
      "Blockchain",
      "Full Stack",
      "AR & VR",
      "Cyber Security",
    ],
    learnings: [
      "Explored cutting-edge Industry 4.0 technologies",
      "Understood AI and machine learning fundamentals",
      "Learned IoT architecture and applications",
      "Gained insights into blockchain technology",
      "Covered full-stack development concepts",
    ],
    validThrough: null,
    credentialId: "XG9JC5M2BF",
  },
  {
    id: 7,
    title: "Internship in Data Science",
    issuer: "Spectrum Softtech Solutions Pvt. Ltd.",
    year: "2021",
    date: "Nov 2021 - Dec 2021",
    certificateUrl: "#",
    image: "/certificates/data-science-internship.jpg",
    featured: false,
    description:
      "Practical data science internship involving real-world data analysis, machine learning models, and data visualization.",
    skills: [
      "Data Science",
      "Machine Learning",
      "Data Analysis",
      "Python",
      "Data Visualization",
    ],
    learnings: [
      "Applied data preprocessing and cleaning techniques",
      "Built and evaluated machine learning models",
      "Created data visualizations and dashboards",
      "Worked on real-world data science projects",
    ],
    validThrough: "Expired Dec 2021",
    credentialId: "Spec/STC/701121021",
  },
  {
    id: 8,
    title: "Bachelor of Technology in Computer Science and Engineering",
    issuer: "APJ Abdul Kalam Technological University",
    year: "2023",
    date: "Aug 2, 2023",
    certificateUrl: "#",
    image: "/certificates/degree-certificate.jpg",
    featured: true,
    description:
      "Four-year undergraduate degree program in Computer Science and Engineering with comprehensive software development and computer science fundamentals.",
    skills: [
      "Software Engineering",
      "Algorithms & Data Structures",
      "Database Systems",
      "Computer Networks",
      "Web Technologies",
      "System Design",
    ],
    learnings: [
      "Comprehensive computer science fundamentals",
      "Advanced software engineering principles",
      "Algorithm design and analysis techniques",
      "Database management and design",
      "Web and mobile application development",
      "System architecture and design patterns",
    ],
    validThrough: null,
    credentialId: "NCE19CS004",
    cgpa: "7.12",
    classification: "First Class",
  },
];

export const PROJECT_SLUG_MAPPING = {
  // B.Tech Computer Science Projects
  "Final Year Project: Full-stack web application for college management system with role-based access control":
    "hospital-management-system",
  "Mini Project: E-commerce platform using MERN stack with payment gateway integration":
    "zigma-watches",
  "Database Project: Library management system with advanced SQL queries and triggers":
    "library-management-system",
  "Web Development: Responsive portfolio website with modern UI/UX principles":
    "portfolio-website",

  // MERN Stack Training Projects
  "E-commerce Platform: Full-featured online shopping system with admin panel, user authentication, cart management, payment integration (Stripe/Razorpay), and order tracking":
    "zigma-watches",
  "Social Media Application: Real-time chat, post sharing, likes, comments, friend requests, notifications using Socket.io":
    "trend-trove",
  "Project Management Tool: Kanban-style task management with drag-and-drop, team collaboration, and deadline tracking":
    "smart-task-manager",
  "Video Streaming Platform: Netflix-like streaming service with video upload, categorization, search, and user subscriptions":
    "netflix-ui-clone",
  "Blog Platform: Content management system with rich text editor, categories, tags, and SEO optimization":
    "blog-platform",

  // Software Engineer AFC Digital Projects
  "Healthcare Management System: Patient records, appointments, billing, and reporting":
    "art-health",
  "Checkpoint System: Multi-tenant access control with real-time monitoring":
    "checkpoint-systems",
  "Dynamic Form Builder: Drag-and-drop form creation with conditional logic":
    "dynamic-form-builder",
  "Automated Workflow Engine: Business process automation with approval chains":
    "workflow-engine",

  // NPM Package
  "db-connections-util: Secure database connection utility for multiple database types":
    "db-connections-util",
};

// Journey Timeline
export const JOURNEY_STEPS = [
  {
    id: 1,
    slug: "btech-computer-science",
    year: "2019-2023",
    title: "B.Tech - Computer Science",
    company: "Nehru College",
    company2: "Nehru College of Engineering",
    location: "Pambady, Thrissur, Kerala, India",
    website: "https://www.ncerc.ac.in/",
    description:
      "Began my journey in Computer Science and Engineering at APJ Abdul Kalam Technological University, building a strong foundation in programming and software development.",
    icon: GraduationCap,
    color: "bg-purple-500",
    image: [PROJECT_IMG_1, PROJECT_IMG_2],
    detailedInfo: {
      degree: "Bachelor of Technology (B.Tech)",
      specialization: "Computer Science and Engineering",
      university: "Kerala Technological University (KTU)",
      duration: "4 Years",
      highlights: [
        "Graduated with strong fundamentals in Data Structures and Algorithms",
        "Completed multiple projects in web development and software engineering",
        "Participated in coding competitions and hackathons",
        "Learned programming languages: C, C++, Java, Python, JavaScript",
        "Built academic projects using modern web technologies",
        "Developed strong problem-solving and analytical skills",
        "Worked on team projects fostering collaboration and communication",
        "Gained exposure to software development lifecycle",
      ],
      keyProjects: [
        "Final Year Project: Full-stack web application for college management system with role-based access control",
        "Mini Project: E-commerce platform using MERN stack with payment gateway integration",
        "Database Project: Library management system with advanced SQL queries and triggers",
        "Web Development: Responsive portfolio website with modern UI/UX principles",
      ],
      coursework: [
        "Data Structures and Algorithms",
        "Database Management Systems",
        "Operating Systems",
        "Computer Networks",
        "Software Engineering",
        "Web Technologies",
        "Object-Oriented Programming",
        "Design and Analysis of Algorithms",
        "Compiler Design",
        "Artificial Intelligence",
      ],
      achievements: [
        "Consistently maintained good academic performance throughout the course",
        "Successfully completed all lab courses with practical implementations",
        "Presented technical seminars on emerging technologies",
        "Participated in inter-college technical events",
      ],
    },
  },
  {
    id: 2,
    slug: "mern-stack-training",
    year: "2023-2024",
    title: "MERN Stack Training",
    company: "Brototype Institute",
    location: "Kochi, Kerala, India",
    website: "https://www.brototype.com/",
    description:
      "Intensive training in MERN stack technologies, learning modern web development practices, Clean Architecture, and building production-ready applications.",
    icon: Code,
    color: "bg-green-500",
    image: [
      PROJECT_IMG_1,
      PROJECT_IMG_2,
      PROJECT_IMG_3,
      PROJECT_IMG_4,
      PROJECT_IMG_5,
      PROJECT_IMG_6,
    ],
    detailedInfo: {
      program: "Full Stack Development - MERN",
      duration: "12 Months",
      type: "Hands-on Professional Training",
      highlights: [
        "Mastered MongoDB, Express.js, React.js, and Node.js ecosystem",
        "Built 15+ full-stack projects from scratch with real-world complexity",
        "Learned Clean Architecture and SOLID principles for scalable code",
        "Implemented RESTful APIs and microservices architecture",
        "Gained expertise in state management with Redux and Context API",
        "Practiced Agile methodologies and Git workflows in team environments",
        "Developed real-time applications using Socket.io and WebSockets",
        "Deployed applications on AWS, Heroku, and Vercel with CI/CD pipelines",
        "Learned to write clean, maintainable, and testable code",
        "Worked on collaborative projects with version control best practices",
      ],
      majorProjects: [
        "E-commerce Platform: Full-featured online shopping system with admin panel, user authentication, cart management, payment integration (Stripe/Razorpay), and order tracking",
        "Social Media Application: Real-time chat, post sharing, likes, comments, friend requests, notifications using Socket.io",
        "Project Management Tool: Kanban-style task management with drag-and-drop, team collaboration, and deadline tracking",
        "Video Streaming Platform: Netflix-like streaming service with video upload, categorization, search, and user subscriptions",
        "Blog Platform: Content management system with rich text editor, categories, tags, and SEO optimization",
      ],
      technologiesLearned: [
        "React.js & Next.js",
        "Node.js & Express.js",
        "MongoDB & Mongoose ODM",
        "Redux Toolkit & Context API",
        "Socket.io for Real-time Communication",
        "JWT & OAuth Authentication",
        "Payment Integration (Stripe, Razorpay)",
        "AWS S3, EC2, CloudFront",
        "Docker & Container Orchestration",
        "Git, GitHub, GitLab",
        "RESTful API Design",
        "Postman & API Testing",
      ],
      learnings: [
        "Full-stack development workflow from design to deployment",
        "Building scalable applications with clean architecture",
        "Database design and optimization techniques",
        "Security best practices including authentication and authorization",
        "Performance optimization and code profiling",
        "Responsive design and mobile-first approach",
        "Team collaboration and code review processes",
        "Problem-solving and debugging complex applications",
      ],
    },
  },
  {
    id: 3,
    slug: "software-engineer-afc-digital",
    year: "2024 - Present",
    title: "Software Engineer",
    company: "AFC Digital Pvt Ltd",
    location: "Bengaluru, Karnataka, India",
    website: "https://www.afcdigital.in/",
    description:
      "Working as a Software Engineer on enterprise applications with multi-tenant architecture, dynamic UI components, and automated workflows for healthcare and checkpoint systems.",
    icon: Briefcase,
    color: "bg-orange-500",
    image: [
      PROJECT_IMG_1,
      PROJECT_IMG_2,
      PROJECT_IMG_3,
      PROJECT_IMG_4,
      PROJECT_IMG_5,
      PROJECT_IMG_6,
    ],
    detailedInfo: {
      role: "Software Engineer",
      department: "Product Development",
      type: "Full-time Position",
      duration: "Present",
      highlights: [
        "Developing enterprise-level multi-tenant applications from scratch",
        "Built dynamic form builders with drag-and-drop functionality for custom workflows",
        "Implemented automated workflow systems for complex business processes",
        "Created reusable component libraries for improved scalability and maintainability",
        "Working on healthcare management systems and checkpoint solutions",
        "Collaborating with cross-functional teams using Agile/Scrum methodology",
        "Optimized application performance for handling large datasets (10,000+ records)",
        "Mentoring junior developers and conducting thorough code reviews",
        "Implemented CI/CD pipelines for automated testing and deployment",
        "Participated in architecture discussions and technical decision-making",
      ],
      responsibilities: [
        "Full-stack development using React.js, Node.js, and modern frameworks",
        "Designing and implementing RESTful APIs with proper documentation",
        "Database design and optimization with PostgreSQL and MongoDB",
        "Implementing secure authentication and role-based authorization systems",
        "Writing clean, maintainable, and testable code following best practices",
        "Participating in sprint planning, daily standups, and retrospectives",
        "Deploying and monitoring applications in production environments",
        "Debugging and resolving production issues with minimal downtime",
        "Creating technical documentation for features and APIs",
        "Collaborating with designers, QA, and product managers",
      ],
      technologies: [
        "React.js & TypeScript",
        "Node.js & Express.js",
        "PostgreSQL & MongoDB",
        "Redis for Caching",
        "Docker & Kubernetes",
        "AWS Services (EC2, S3, RDS)",
        "Git, GitHub, Jira",
        "Jest & React Testing Library",
        "Nginx & Load Balancing",
        "Microservices Architecture",
      ],
      achievements: [
        "Reduced API response time by 40% through query optimization and caching",
        "Built a dynamic form builder that's now used across 3 different products",
        "Successfully delivered 5+ major features within tight deadlines",
        "Improved code coverage from 30% to 80% through comprehensive testing",
        "Resolved critical production bugs with 99.9% uptime maintained",
        "Implemented automated workflows saving 10+ hours of manual work per week",
      ],
      projects: [
        "Healthcare Management System: Patient records, appointments, billing, and reporting",
        "Checkpoint System: Multi-tenant access control with real-time monitoring",
        "Dynamic Form Builder: Drag-and-drop form creation with conditional logic",
        "Automated Workflow Engine: Business process automation with approval chains",
      ],
    },
  },
  {
    id: 4,
    slug: "npm-package-db-connections-util",
    year: "2024",
    title: "Published NPM Package: db-connections-util",
    company: "Open Source Contribution",
    location: "Remote",
    website: "https://www.npmjs.com/package/db-connections-util",
    description:
      "Released db-connections-util, a secure database connection utility supporting multiple database types with AES-256 encryption, available on NPM for the developer community.",
    icon: Package,
    color: "bg-pink-500",
    image: [
      PROJECT_IMG_1,
      PROJECT_IMG_2,
      PROJECT_IMG_3,
      PROJECT_IMG_4,
      PROJECT_IMG_5,
      PROJECT_IMG_6,
    ],
    detailedInfo: {
      packageName: "db-connections-util",
      type: "Open Source NPM Package",
      version: "Latest Stable Release",
      downloads: "500+ downloads",
      highlights: [
        "Created a production-ready database connection utility package from scratch",
        "Implemented AES-256 encryption for secure credential storage",
        "Supports multiple databases: PostgreSQL, MySQL, MongoDB, Redis",
        "Comprehensive documentation with usage examples and API reference",
        "Published to NPM registry for global developer community access",
        "Handles connection pooling and automatic reconnection logic",
        "Built with TypeScript for type safety and better developer experience",
        "Includes unit tests with 95% code coverage using Jest",
        "Semantic versioning and changelog for version tracking",
        "Active maintenance and community support",
      ],
      features: [
        "Secure credential encryption using AES-256-CBC algorithm",
        "Support for PostgreSQL, MySQL, MongoDB, and Redis",
        "Connection pooling for optimized database access",
        "Automatic retry and reconnection with exponential backoff",
        "Environment-based configuration with .env support",
        "TypeScript support with complete type definitions",
        "Comprehensive error handling with custom error types",
        "Easy integration with Express.js and other Node.js frameworks",
        "Minimal dependencies for lightweight package",
        "Cross-platform compatibility (Windows, Linux, macOS)",
      ],
      technologies: [
        "Node.js & TypeScript",
        "Crypto Module (AES-256)",
        "pg (PostgreSQL Driver)",
        "mysql2 (MySQL Driver)",
        "mongodb (MongoDB Driver)",
        "redis (Redis Client)",
        "Jest for Testing",
        "ESLint & Prettier",
        "NPM Publishing",
      ],
      impact: [
        "Simplified secure database connections for Node.js developers",
        "Improved application security with built-in encryption",
        "Saved development time across multiple projects and teams",
        "Contributing to the open-source ecosystem",
        "Helping developers avoid common database connection pitfalls",
        "Active community engagement with issue resolution",
      ],
      useCases: [
        "Express.js applications needing secure database connections",
        "Microservices requiring multiple database support",
        "Projects needing encrypted credential storage",
        "Applications requiring connection pooling and retry logic",
      ],
      futureEnhancements: [
        "Support for additional databases (SQL Server, Oracle)",
        "CLI tool for connection testing",
        "Performance monitoring and metrics",
        "Connection health checks and diagnostics",
      ],
    },
  },
];
